//
//  Pickup.swift
//  MySampleApp
//
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.2
//

import Foundation
import UIKit
import AWSDynamoDB

class Pickup: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _pinId: String?
    var _waypointId: String?
    var _timestamp: NSNumber?
    var _userId: String?
    
    class func dynamoDBTableName() -> String {

        return "tripple-mobilehub-1169331636-Pickup"
    }
    
    class func hashKeyAttribute() -> String {

        return "_pinId"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_waypointId"
    }
    
    override class func JSONKeyPathsByPropertyKey() -> [NSObject : AnyObject] {
        return [
               "_pinId" : "pinId",
               "_waypointId" : "waypointId",
               "_timestamp" : "timestamp",
               "_userId" : "userId",
        ]
    }
    
    static func ignoreAttributes() -> [String] {
        return ["createdDate"]
    }
    
    // additions
    
    var createdDate: NSDate? {
        get {
            if let interval = _timestamp {
                return NSDate(timeIntervalSince1970: interval.doubleValue)
            }
            return nil
        }
        set {
            if let interval = newValue?.timeIntervalSince1970 {
                _timestamp = NSNumber(double: interval)
                return
            }
            _timestamp = nil
        }
    }
    
    override init() {
        super.init()
    }
    
    override init(dictionary dictionaryValue: [NSObject : AnyObject]!, error: ()) throws {
        try super.init(dictionary: dictionaryValue, error: error)
    }
    
    convenience init(pin: Pin, waypoint: Waypoint, userId: String) {
        self.init()
        
        self._pinId = pin._id
        self._waypointId = waypoint._id
        self._userId = userId
        self.createdDate = NSDate()
    }
    
    required init!(coder: NSCoder!) {
        fatalError("init(coder:) has not been implemented")
    }

}
