//
//  Pin.swift
//  MySampleApp
//
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.2
//

import Foundation
import UIKit
import AWSDynamoDB

class Pin: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _id: String?
    var _message: String?
    var _title: String?
    
    class func dynamoDBTableName() -> String {

        return "tripple-mobilehub-1169331636-Pin"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_id"
    }
    
    override class func JSONKeyPathsByPropertyKey() -> [NSObject : AnyObject] {
        return [
               "_userId" : "userId",
               "_id" : "id",
               "_message" : "message",
               "_title" : "title",
        ]
    }
    
    override init() {
        super.init()
    }
    
    convenience init(title: String, message: String? = nil) {
        self.init()

        self._title = title
        self._message = message
    }
    
    required init!(coder: NSCoder!) {
        fatalError("init(coder:) has not been implemented")
    }

}
