//
//  Waypoint.swift
//  MySampleApp
//
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.2
//

import CoreLocation
import Foundation
import UIKit

import AWSDynamoDB

class Waypoint: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _id: String?
    var _location: [String: String]?
    var _pinId: String?
    var _previousWaypointId: String?
    var _timestamp: NSNumber?
    
    class func dynamoDBTableName() -> String {

        return "tripple-mobilehub-1169331636-Waypoint"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
    
    override class func JSONKeyPathsByPropertyKey() -> [NSObject : AnyObject] {
        return [
               "_userId" : "userId",
               "_id" : "id",
               "_location" : "location",
               "_pinId" : "pinId",
               "_previousWaypointId" : "previousWaypointId",
               "_timestamp" : "timestamp",
        ]
    }
    
    static func ignoreAttributes() -> [String] {
        return ["dropLocation", "createdDate"]
    }
    
    // additions
    
    var latitude: CLLocationDegrees? {
        guard let value = _location?["latitude"] else { return nil }
        return (value as NSString).doubleValue
    }
    
    var longitude: CLLocationDegrees? {
        guard let value = _location?["longitude"] else { return nil }
        
        return (value as NSString).doubleValue
    }
    
    var altitude: CLLocationDegrees? {
        guard let value = _location?["altitude"] else { return nil }
        return (value as NSString).doubleValue
    }
    
    var dropLocation: CLLocation? {
        get {
            guard let latitude = latitude, let longitude = longitude else { return nil }
            return CLLocation(latitude: latitude, longitude: longitude)
        }
        set {
            _location = [
                "latitude": newValue != nil ? "\(newValue!.coordinate.latitude)" : "",
                "longitude": newValue != nil ? "\(newValue!.coordinate.longitude)" : "",
                "altitude": newValue != nil ? "\(newValue!.altitude)" : "",
            ]
        }
    }
    
    var createdDate: NSDate? {
        get {
            if let interval = _timestamp {
                return NSDate(timeIntervalSince1970: interval.doubleValue)
            }
            return nil
        }
        set {
            if let interval = newValue?.timeIntervalSince1970 {
                _timestamp = NSNumber(double: interval)
                return
            }
            _timestamp = nil
        }
    }
    
    override init() {
        super.init()
    }
    
    override init(dictionary dictionaryValue: [NSObject : AnyObject]!, error: ()) throws {
        try super.init(dictionary: dictionaryValue, error: error)
    }
    
    convenience init(pin: Pin, location: CLLocation, previousWaypoint: Waypoint? = nil) {
        self.init()
        
        self._pinId = pin._id
        self.dropLocation = location
        self._previousWaypointId = previousWaypoint?._id
    }
    
    required init!(coder: NSCoder!) {
        fatalError("init(coder:) has not been implemented")
    }
    
}
